-- AlterTable
ALTER TABLE "LearningFatigueMetric" ALTER COLUMN "date" DROP NOT NULL,
ALTER COLUMN "comprehension_confidence" DROP NOT NULL,
ALTER COLUMN "course_id" DROP NOT NULL,
ALTER COLUMN "distraction_events" DROP NOT NULL,
ALTER COLUMN "duration_minutes" DROP NOT NULL,
ALTER COLUMN "instruction_method" DROP NOT NULL,
ALTER COLUMN "module_id" DROP NOT NULL,
ALTER COLUMN "mood_after" DROP NOT NULL,
ALTER COLUMN "mood_before" DROP NOT NULL,
ALTER COLUMN "num_attempts_quiz" DROP NOT NULL,
ALTER COLUMN "num_pauses" DROP NOT NULL,
ALTER COLUMN "opened_feedback" DROP NOT NULL,
ALTER COLUMN "perceived_cognitive_load" DROP NOT NULL,
ALTER COLUMN "quiz_score" DROP NOT NULL,
ALTER COLUMN "sleep_hours_prev_night" DROP NOT NULL,
ALTER COLUMN "start_time" DROP NOT NULL,
ALTER COLUMN "stress_level" DROP NOT NULL,
ALTER COLUMN "student_id" DROP NOT NULL,
ALTER COLUMN "task_difficulty_rating" DROP NOT NULL,
ALTER COLUMN "time_to_complete_quiz_seconds" DROP NOT NULL,
ALTER COLUMN "time_to_open_feedback_hours" DROP NOT NULL;
