import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import NextAuthProvider from "@/providers/NextAuthProvider";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import { Toaster } from "@/components/ui/sonner";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "500", "600", "700"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    const session = await getServerSession(authOptions);

    return (
        <html lang="en" className="dark" suppressHydrationWarning>
            <body className={`${poppins.className} antialiased`}>
                <NextAuthProvider session={session}>
                    <Toaster richColors position="bottom-right" />
                    <ReactQueryProvider>
                        {children}
                    </ReactQueryProvider>
                </NextAuthProvider>
            </body>
        </html>
    );
}
